config/routes.rb
Rails.application.routes.draw do



  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"



  get 'bash_fill', to: 'pages#bash_fill'
  get 'bash_fill_detail', to: 'pages#bash_fill_detail'
  patch :bash_fill_detail, to: "pages#update_many_details", as: :update_many_details
  get  :bash_fill_report,  to: "pages#bash_fill_report"
  patch :bash_fill_report, to: "pages#update_many_reports", as: :update_many_reports

  resources :details
  resources :ladder_details
  resources :reports
  resources :items do
    member do
      get 'edit_identificador'
      patch 'update_identificador'
      get 'edit_empresa'
      patch 'update_empresa'
      get 'edit_group'
      patch 'update_group'
    end
  end
  root 'home#index', as: 'home'

  post 'check_all_expirations', to: 'home#check_all_expirations', as: :check_all_expirations

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :authentication, path: '', as: '' do
    resources :users, path: '/users' do
      collection do
        get :new_client
        post :create_client
      end
      member do
        get :edit_client
        patch :update_client
        get :manage_permisos
        patch :update_permisos
      end
    end
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  namespace :api do
    namespace :v1 do
      resources :facturacions, only: [:index, :show]
    end
  end


  resources :users, only: :show, path: '/user', param: :username, as: 'perfil' do
    member do
      patch :toggle_tabla
    end
  end


  resources :inspections, path: '/inspections' do
    member do
      get :download_document
      patch :close_inspection
      patch :update_ending
      get :download_json
      patch :update_inf_date
      get :new_with_last
      patch :force_close_inspection
      get :edit_informe
      patch :update_informe
      get :download_informe
      get :search_candidates
      get :copy_preview
      patch :copy
      get   :edit_certificacion
      patch :update_certificacion
      get   :download_certificacion
    end

    #get :download_images
    collection do
      get :edit_massive_load
      patch :update_massive_load
      get :export_xlsx
      patch :bulk_ignore
      patch :bulk_unignore
    end

  end

  resources :graficos, only: [:index], path: '/graficos' do
    collection do
      get :certificados_excel
    end
  end

  resources :groups, only: [:new, :create, :index, :show, :destroy], path: '/groups' do
    collection do
      get 'libre', to: 'groups#libre', as: 'libre'
    end
  end
  resources :rules  , path: '/rules' do
    collection do
      get :new_with_new_code
      get :new_with_same_code
      post :create_with_new_code
      post :create_with_same_code
      get :new_import
      post :import
    end
  end

  resources :ruletypes, only: [:new, :create, :index, :destroy, :show], path: '/ruletypes' do
    collection do
      get :new_import
      post :import
    end
  end
  resources :ladders, path: '/ladders' do
    collection do
      get :new_import
      post :import
    end
  end

  resources :rules_plats, path: '/rules_plats' do
    collection do
      get :new_import
      post :import
    end
  end

  resources :plat_revisions, path: '/plat_revisions' do
    member do
      get 'new_rule', to: 'plat_revisions#new_rule'
      post 'create_rule', to: 'plat_revisions#create_rule'
      get   :edit_rule
      patch :update_rule
    end
  end

  resources :items, path: '/items'
  resources :principals, path: '/principals' do
    get :items, on: :member
    get :places, on: :member
    get :no_conformidad
    get :estado_activos
    get :defectos_activos
  end
  resources :revisions, path: '/revisions' do
    member do
      #get 'edit_libre', to: 'revisions#edit_libre'
      get 'new_rule', to: 'revisions#new_rule'
      post 'create_rule', to: 'revisions#create_rule'
      get   :edit_rule
      patch :update_rule
    end
  end


  resources :ladder_revisions, path: '/ladder_revisions'

  resources :revision_photos, only: [:destroy] do
    member do
      patch :rotate
    end
  end
  resource :demo_email, only: :show

  resources :facturacions, only: [:new, :create, :index, :edit, :update, :show, :destroy], path: 'cotizaciones' do

    member do
      get :download_solicitud_file
      get :download_cotizacion_doc_file
      get :download_cotizacion_pdf_file
      get :download_orden_compra_file
      get :download_facturacion_file
      get :download_all_files
      patch :upload_cotizacion
      patch :marcar_entregado
      patch :upload_orden_compra      
      patch :update_fecha_entrega
      patch :upload_factura
      get :manage_files
      patch :replace_file
      get :download_solicitud_template
      get :download_cotizacion_template
      get :download_cotizacion_template_og
      patch :update_price
      patch :set_fecha_venta
      patch :update_fecha_venta
      patch :update_empresa_provisional
      patch :update_n1

    end
    collection do
      get :new_bulk_upload
      post :bulk_upload
      get :new_bulk_upload_pdf
      post :bulk_upload_pdf
      get :download_all_excel
      get :export_xlsx
      get :export_monthly_report
    end


    resources :observacions, only: [:create, :edit, :update, :destroy]
  end

  resources :convenios

  resources :permisos


  get 'warnings', to: 'static_pages#warnings'
  get 'info', to: 'static_pages#info'
  get 'empresas.xlsx', to: 'static_pages#export_empresas_xlsx', as: :export_empresas
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/group.rb
#La clasificación de los ascensores, de esto depende que defectos se evaluan
class Group < ApplicationRecord
  validates :number, presence: true, uniqueness: true, non_negative: true
  validates :name, presence: true, uniqueness: true
  validates :type_of, inclusion: { in: %w[ascensor escala libre plat], message: "%{value} no es un tipo válido" }


  attribute :number, :integer, default: -> { calculate_new_number }

  ORDER_BY = {
    newest: "created_at DESC",
  }

  has_many :items, dependent: :restrict_with_error
  has_many :rulesets, dependent: :destroy
  has_many :revisions
  has_many :rules, through: :rulesets
  has_many :rules_plats
  has_many :plat_revisions
  accepts_nested_attributes_for :rules

  TYPE_TO_ASSOC = {
    "escala"   => :ladder_revision,
    "ascensor" => :revision,
    "plat"     => :plat_revision
  }.freeze

  def revision_for(object)
    method = TYPE_TO_ASSOC[type_of]
    return nil unless method

    object.public_send(method)
  end

  def revision_for!(object)
    method = TYPE_TO_ASSOC.fetch(type_of) do
      raise ArgumentError, "type_of no soportado: #{type_of.inspect}"
    end
    object.public_send(method)
  end
  private

  #para calcular automaticamente el numero de grupo
  def self.calculate_new_number
    records = Group.order(number: :asc)



    records.each_with_index do |record, index|
      return record.number + 1 if index == (records.size - 1)
      return record.number + 1 if record.number != (records[index+1].number - 1)
    end

    return 1


  end



end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authorize!
  # GET /groups or /groups.json
  def index
    @groups = Group.where.not(type_of: 'libre').order(number: :asc)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  def show
    group
    if group.type_of == "escala"
      @rules = Ladder.all
    else
      @rules = group.rules.ordered_by_code
    end
    if group.type_of == "plat"
      @rules = group.rules_plats.ordered_by_code
    end

    if group.type_of == "libre"
      rules1 = @rules.limit(11)
      rules2 = @rules.offset(11)
      rules2.each_with_index do |rule, index|
        rule.code = (index + 1).to_s + "."
      end
      @rules = rules1 + rules2
    end
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    if @group.secondary_type == 'escala' && Group.exists?(type_of: 'escala')
      flash[:alert] = "Ya existe un grupo con el tipo escala."
      redirect_to new_group_url
    else
      if @group.secondary_type == 'plataforma' || @group.secondary_type == 'salvaescala'
        @group.type_of = 'plat'
      else
        @group.type_of = @group.secondary_type
      end

        if @group.save



          flash[:notice] = "Se creó la clasificación con éxito."
          redirect_to groups_url
        else
          flash.now[:alert] = "No se pudo crear la clasificación."
          render :new, status: :unprocessable_entity
        end
    end
  end



  # DELETE /groups/1 or /groups/1.json
  def destroy

    if group.items.exists?
      flash[:alert] = "No se pudo eliminar el grupo porque tiene elementos asociados."
      redirect_to group_path(group)
    else
      rules = group.rules.to_a

      if group.destroy

        rules.each_with_index do |rule, index|

          if rule.groups.count == 0

            rule.destroy
          end

        end

        flash[:notice] = "Grupo eliminado con éxito."
        respond_to do |format|
          format.html { redirect_to groups_path }
          format.turbo_stream { head :no_content }
        end
      else
        flash[:alert] = "No se pudo eliminar el grupo por un motivo desconocido."
        redirect_to group_path(group)
      end
    end
  end





  def libre
    @groups = Group.where(type_of: 'libre').order(number: :asc)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:number, :name, :type_of, :secondary_type, rules_attributes: [:point])
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: group, builder: CustomFormBuilder, class: "space-y-4 bg-gray-900 text-white p-4 rounded-md shadow-lg") do |form| %>
  <% if group.errors.any? %>
    <% error_messages = group.errors.full_messages.map { |msg| "<li>#{j msg}</li>" }.join %>
    <%= javascript_tag do %>
      Swal.fire({
      icon: 'error',
      title: '¡Atención!',
      html: '<strong>Error: </strong> No se pudo guardar esta clasificación:<br><ul style="text-align: left;">' + '<%= raw error_messages %>' + '</ul>',
      confirmButtonText: 'Entendido'
      })
    <% end %>
  <% end %>



  <div class="flex flex-col mt-4">
    <%= form.label :name, "Nombre de la clasificación:", class: "text-gray-300" %>
    <%= form.text_field :name, maxlength: 100, class: "mt-1 block w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-blue-600 focus:border-blue-600 sm:text-sm" %>
  </div>

  <div class="flex flex-col mt-4">
    <%= form.label :secondary_type, "Tipo de checklist a utilizar:", class: "text-gray-300" %>
    <%= form.select :secondary_type, options_for_select([["Ascensor", "ascensor"], ["Escala", "escala"], ["Plataforma", "plataforma"], ["Salvaescala", "salvaescala"]]), {}, class: "mt-1 block w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md shadow-sm focus:outline-none focus:ring-blue-600 focus:border-blue-600 sm:text-sm" %>
  </div>


  <div class="mt-6 py-5">
    <%= form.submit "Crear clasificación", class: "w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="max-w-xl mx-auto p-5 bg-gray-800 rounded-lg shadow">
  <div>
    <h2 class="text-xl font-bold text-gray-200"><%= group.name %></h2>
  </div>
</div>

app/views/groups/index.html.erb
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 bg-gray-900">

  <h1 class="text-4xl font-bold text-gray-100 mt-6 mb-10 text-center">Clasificaciones</h1>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-4">
    <% @groups.each do |group| %>
      <div class="bg-gray-800 rounded-lg shadow overflow-hidden">
        <div class="p-6">
          <h2 class="text-2xl font-bold text-gray-300 mb-4"><%= group.name %></h2>
          <%= link_to "Ver detalles", group, class: "inline-block px-6 py-2 bg-blue-600 text-white font-bold rounded hover:bg-blue-700 transition duration-300" %>
        </div>
      </div>
    <% end %>


    <% if false %>
      <div class="bg-gray-800 rounded-lg shadow overflow-hidden">
        <div class="p-6">
          <h2 class="text-2xl font-bold text-gray-300 mb-4"> Grupos Libres </h2>
          <%= link_to "Ver Grupos Libres", libre_groups_path, class: "inline-block px-6 py-2 bg-blue-600 text-white font-bold rounded hover:bg-blue-700 transition duration-300" %>
        </div>
      </div>
      <% end %>

  </div>

  <div class="text-center mt-12">
    <%= link_to "Crear nueva clasificación", new_group_path, class: "px-6 py-3 bg-green-600 text-white font-bold rounded hover:bg-green-700 transition duration-300" %>
  </div>
</div>

<div class="text-center mt-12">
  <%= link_to "Ver defectos", rules_path, class: "px-6 py-2 bg-indigo-600 text-white font-bold rounded hover:bg-indigo-700 transition duration-300" %>
</div>

app/views/groups/libre.html.erb
<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 bg-gray-900">

  <h1 class="text-4xl font-bold text-gray-100 mb-10 text-center">Grupos libres</h1>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-4">
    <% @groups.each do |group| %>
      <div class="bg-gray-800 rounded-lg shadow overflow-hidden">
        <div class="p-6">
          <h2 class="text-2xl font-bold text-gray-300 mb-4"><%= group.name %></h2>
          <%= link_to "Ver detalles", group, class: "inline-block px-6 py-2 bg-blue-600 text-white font-bold rounded hover:bg-blue-700 transition duration-300" %>
        </div>
      </div>
    <% end %>
  </div>


</div>

<div class="text-center mt-12">
  <%= link_to "Volver a clasificaciones normales", groups_path, class: "px-6 py-2 bg-indigo-600 text-white font-bold rounded hover:bg-indigo-700 transition duration-300" %>
</div>

app/views/groups/new.html.erb
<div class="max-w-xl mx-auto p-5">
  <h1 class="text-3xl font-bold text-gray-800 mb-6">Crear Nueva Clasificación</h1>

  <div class="mb-6">
    <%= link_to "Volver atrás", groups_path, class: "inline-flex items-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-blue-400 bg-gray-800 hover:bg-blue-800 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 transition duration-150 ease-in-out" %>
  </div>

  <%= render "form", group: @group %>


</div>

app/views/groups/show.html.erb
<%= render @group %>

<div class="flex flex-col sm:flex-row sm:space-x-4 mt-6">
  <%= link_to "Volver a clasificaciones", groups_path, class: "inline-flex items-center px-4 py-2 border border-gray-700 text-sm font-medium rounded-md shadow-sm text-gray-300 bg-blue-500 hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 transition ease-in-out duration-150" %>
  <% if Current.user.admin? %>
    <%= link_to 'Eliminar clasificación', group_path(@group), class: "inline-flex items-center px-4 py-2 border border-gray-700 text-sm font-medium rounded-md shadow-sm text-gray-300 bg-red-700 hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 transition ease-in-out duration-150 mt-2 sm:mt-0", data: { controller: "delete-confirmation", action: "click->delete-confirmation#deleteItem", delete_confirmation_redirect_url_value: "/groups" } %>
  <% end %>
</div>

<div class="bg-gray-800 shadow overflow-hidden sm:rounded-lg mt-4">
  <h3 class="text-lg font-semibold text-gray-200 px-4 py-5 bg-gray-700 border-b border-gray-600">Defectos a revisar:</h3>
  <ul class="divide-y divide-gray-700">
    <% @rules.each do |rule| %>
      <li class="px-4 py-4 bg-gray-800 text-gray-400 hover:bg-gray-700">
        <%= "#{rule.code} #{rule.point}" %>
      </li>
    <% end %>
  </ul>
</div>