config/routes.rb
Rails.application.routes.draw do



  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"



  get 'bash_fill', to: 'pages#bash_fill'
  get 'bash_fill_detail', to: 'pages#bash_fill_detail'
  patch :bash_fill_detail, to: "pages#update_many_details", as: :update_many_details
  get  :bash_fill_report,  to: "pages#bash_fill_report"
  patch :bash_fill_report, to: "pages#update_many_reports", as: :update_many_reports

  resources :details
  resources :ladder_details
  resources :reports
  resources :items do
    member do
      get 'edit_identificador'
      patch 'update_identificador'
      get 'edit_empresa'
      patch 'update_empresa'
      get 'edit_group'
      patch 'update_group'
    end
  end
  root 'home#index', as: 'home'

  post 'check_all_expirations', to: 'home#check_all_expirations', as: :check_all_expirations

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :authentication, path: '', as: '' do
    resources :users, path: '/users' do
      collection do
        get :new_client
        post :create_client
      end
      member do
        get :edit_client
        patch :update_client
        get :manage_permisos
        patch :update_permisos
      end
    end
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  namespace :api do
    namespace :v1 do
      resources :facturacions, only: [:index, :show]
    end
  end


  resources :users, only: :show, path: '/user', param: :username, as: 'perfil' do
    member do
      patch :toggle_tabla
    end
  end


  resources :inspections, path: '/inspections' do
    member do
      get :download_document
      patch :close_inspection
      patch :update_ending
      get :download_json
      patch :update_inf_date
      get :new_with_last
      patch :force_close_inspection
      get :edit_informe
      patch :update_informe
      get :download_informe
      get :search_candidates
      get :copy_preview
      patch :copy
      get   :edit_certificacion
      patch :update_certificacion
      get   :download_certificacion
    end

    #get :download_images
    collection do
      get :edit_massive_load
      patch :update_massive_load
      get :export_xlsx
      patch :bulk_ignore
      patch :bulk_unignore
    end

  end

  resources :graficos, only: [:index], path: '/graficos' do
    collection do
      get :certificados_excel
    end
  end

  resources :groups, only: [:new, :create, :index, :show, :destroy], path: '/groups' do
    collection do
      get 'libre', to: 'groups#libre', as: 'libre'
    end
  end
  resources :rules  , path: '/rules' do
    collection do
      get :new_with_new_code
      get :new_with_same_code
      post :create_with_new_code
      post :create_with_same_code
      get :new_import
      post :import
    end
  end

  resources :ruletypes, only: [:new, :create, :index, :destroy, :show], path: '/ruletypes' do
    collection do
      get :new_import
      post :import
    end
  end
  resources :ladders, path: '/ladders' do
    collection do
      get :new_import
      post :import
    end
  end

  resources :rules_plats, path: '/rules_plats' do
    collection do
      get :new_import
      post :import
    end
  end

  resources :plat_revisions, path: '/plat_revisions' do
    member do
      get 'new_rule', to: 'plat_revisions#new_rule'
      post 'create_rule', to: 'plat_revisions#create_rule'
      get   :edit_rule
      patch :update_rule
    end
  end

  resources :items, path: '/items'
  resources :principals, path: '/principals' do
    get :items, on: :member
    get :places, on: :member
    get :no_conformidad
    get :estado_activos
    get :defectos_activos
  end
  resources :revisions, path: '/revisions' do
    member do
      #get 'edit_libre', to: 'revisions#edit_libre'
      get 'new_rule', to: 'revisions#new_rule'
      post 'create_rule', to: 'revisions#create_rule'
      get   :edit_rule
      patch :update_rule
    end
  end


  resources :ladder_revisions, path: '/ladder_revisions'

  resources :revision_photos, only: [:destroy] do
    member do
      patch :rotate
    end
  end
  resource :demo_email, only: :show

  resources :facturacions, only: [:new, :create, :index, :edit, :update, :show, :destroy], path: 'cotizaciones' do

    member do
      get :download_solicitud_file
      get :download_cotizacion_doc_file
      get :download_cotizacion_pdf_file
      get :download_orden_compra_file
      get :download_facturacion_file
      get :download_all_files
      patch :upload_cotizacion
      patch :marcar_entregado
      patch :upload_orden_compra      
      patch :update_fecha_entrega
      patch :upload_factura
      get :manage_files
      patch :replace_file
      get :download_solicitud_template
      get :download_cotizacion_template
      get :download_cotizacion_template_og
      patch :update_price
      patch :set_fecha_venta
      patch :update_fecha_venta
      patch :update_empresa_provisional
      patch :update_n1

    end
    collection do
      get :new_bulk_upload
      post :bulk_upload
      get :new_bulk_upload_pdf
      post :bulk_upload_pdf
      get :download_all_excel
      get :export_xlsx
      get :export_monthly_report
    end


    resources :observacions, only: [:create, :edit, :update, :destroy]
  end

  resources :convenios

  resources :permisos


  get 'warnings', to: 'static_pages#warnings'
  get 'info', to: 'static_pages#info'
  get 'empresas.xlsx', to: 'static_pages#export_empresas_xlsx', as: :export_empresas
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flash.html.erb
<%= turbo_frame_tag 'flash', data: { turbo_temporary: "true" } do %>
  <% if alert %>
    <% alert_type = flash[:alert_type] || "error" %>
    <% alert_title = case alert_type
                     when "info" then "Información"
                     when "warning" then "Advertencia"
                     else "Error"
                     end %>
    <%= javascript_tag do %>
      Swal.fire({
      icon: '<%= j alert_type %>',
      title: '<%= j alert_title %>',
      text: '<%= j alert %>',
      confirmButtonText: 'OK'
      });
    <% end %>
  <% elsif notice %>
    <div class="max-w-lg mx-auto mt-4 p-4 bg-green-100 border border-green-400 text-green-700 rounded">
      <h2 class="text-center font-bold"><%= notice %></h2>
    </div>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<div class="flex items-start">
  <% unless request.path =~ /\/revisions\/\d+\/edit/ || request.path =~ /\/ladder_revisions\/\d+\/edit/ %>
    <div class="mr-4">
      <%= link_to image_tag("logo-header.png", alt: "Chilena de Certificaciones", class: "h-16 w-auto cursor-pointer"), "#{home_path}", class: "inline-block" %>
    </div>
  <% end %>


  <% if Current.user %>
  <div class="flex flex-col ml-2">
    <div class="text-lg font-semibold">
      <%= Current.user.real_name %>
    </div>
    <div class="text-lg font-semibold">
      <% if Current.user.admin %>
        <%= "Certificador" %>
      <% elsif Current.user.empresa == nil %>
        <%= "Inspector" %>
      <% else %>
        <%= Current.user.empresa %>
      <% end %>
    </div>
  </div>

<% end %>


</div>


<div class="flex justify-between items-center mt-4 px-4">
  <div class="bg-gray-800 p-2 rounded-lg flex justify-between w-full">
    <div>
      <%= link_to 'Usuarios', users_path, class: "text-blue-500 hover:text-blue-700" if Current.user&.admin %>
    </div>

    <% unless request.path =~ /\/revisions\/\d+\/edit/ || request.path =~ /\/ladder_revisions\/\d+\/edit/ %>

      <div class="flex items-center">
        <%= link_to raw('<svg class="h-4 w-4 text-blue-600 inline-block mr-2 align-middle" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/>
          </svg> Home'), home_path, class: "text-lg text-blue-600 hover:text-blue-700 font-semibold transition duration-150 ease-in-out" %>
      </div>
    <% end %>

    <div class="flex">
      <%= link_to 'Mi perfil', perfil_path(Current.user.username), class: "text-green-500 hover:text-green-700" if Current.user %>
      <%= link_to 'Cerrar sesión', session_path(Current.user.id), class: "text-red-600 hover:text-red-800 ml-4", data: { controller: "logout-confirmation", action: "click->logout-confirmation#deleteSession", delete_confirmation_redirect_url_value: home_path } if Current.user %>
    </div>

  </div>


</div>

app/views/shared/_search_form.html.erb
<%= form_with url: form_url, method: :get, local: true, scope: :q, data: { controller: "search", action: "search#toggleClearButton", search_target: "form" } do |form| %>
  <div class="flex flex-wrap gap-4 mb-6 items-center">
    <%= form.search_field search_keys, placeholder: "Buscar por #{placeholder_text}", onchange: 'this.form.requestSubmit()', value: params.dig(:q, search_keys), class: "shadow appearance-none border rounded py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline flex-grow", data: { search_target: "searchField" } %>
    <%= form.button 'Buscar', type: 'submit', class: "bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mr-2 flex-shrink-0" %>

    <div data-search-target="clearButton" style="display: none;">
      <%= button_tag type: 'submit', form: form_url, method: :get, class: 'bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline ml-2 flex-shrink-0', data: { action: "click->search#resetSearch" } do %>
        Limpiar filtro
      <% end %>
    </div>
  </div>
<% end %>