config/routes.rb
Rails.application.routes.draw do



  get "/service-worker.js" => "service_worker#service_worker"
  get "/manifest.json" => "service_worker#manifest"



  get 'bash_fill', to: 'pages#bash_fill'
  get 'bash_fill_detail', to: 'pages#bash_fill_detail'
  patch :bash_fill_detail, to: "pages#update_many_details", as: :update_many_details
  get  :bash_fill_report,  to: "pages#bash_fill_report"
  patch :bash_fill_report, to: "pages#update_many_reports", as: :update_many_reports

  resources :details
  resources :ladder_details
  resources :reports
  resources :items do
    member do
      get 'edit_identificador'
      patch 'update_identificador'
      get 'edit_empresa'
      patch 'update_empresa'
      get 'edit_group'
      patch 'update_group'
    end
  end
  root 'home#index', as: 'home'

  post 'check_all_expirations', to: 'home#check_all_expirations', as: :check_all_expirations

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  namespace :authentication, path: '', as: '' do
    resources :users, path: '/users' do
      collection do
        get :new_client
        post :create_client
      end
      member do
        get :edit_client
        patch :update_client
        get :manage_permisos
        patch :update_permisos
      end
    end
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
  end

  namespace :api do
    namespace :v1 do
      resources :facturacions, only: [:index, :show]
    end
  end


  resources :users, only: :show, path: '/user', param: :username, as: 'perfil' do
    member do
      patch :toggle_tabla
    end
  end


  resources :inspections, path: '/inspections' do
    member do
      get :download_document
      patch :close_inspection
      patch :update_ending
      get :download_json
      patch :update_inf_date
      get :new_with_last
      patch :force_close_inspection
      get :edit_informe
      patch :update_informe
      get :download_informe
      get :search_candidates
      get :copy_preview
      patch :copy
      get   :edit_certificacion
      patch :update_certificacion
      get   :download_certificacion
    end

    #get :download_images
    collection do
      get :edit_massive_load
      patch :update_massive_load
      get :export_xlsx
      patch :bulk_ignore
      patch :bulk_unignore
    end

  end

  resources :graficos, only: [:index], path: '/graficos' do
    collection do
      get :certificados_excel
    end
  end

  resources :groups, only: [:new, :create, :index, :show, :destroy], path: '/groups' do
    collection do
      get 'libre', to: 'groups#libre', as: 'libre'
    end
  end
  resources :rules  , path: '/rules' do
    collection do
      get :new_with_new_code
      get :new_with_same_code
      post :create_with_new_code
      post :create_with_same_code
      get :new_import
      post :import
    end
  end

  resources :ruletypes, only: [:new, :create, :index, :destroy, :show], path: '/ruletypes' do
    collection do
      get :new_import
      post :import
    end
  end
  resources :ladders, path: '/ladders' do
    collection do
      get :new_import
      post :import
    end
  end

  resources :rules_plats, path: '/rules_plats' do
    collection do
      get :new_import
      post :import
    end
  end

  resources :plat_revisions, path: '/plat_revisions' do
    member do
      get 'new_rule', to: 'plat_revisions#new_rule'
      post 'create_rule', to: 'plat_revisions#create_rule'
      get   :edit_rule
      patch :update_rule
    end
  end

  resources :items, path: '/items'
  resources :principals, path: '/principals' do
    get :items, on: :member
    get :places, on: :member
    get :no_conformidad
    get :estado_activos
    get :defectos_activos
  end
  resources :revisions, path: '/revisions' do
    member do
      #get 'edit_libre', to: 'revisions#edit_libre'
      get 'new_rule', to: 'revisions#new_rule'
      post 'create_rule', to: 'revisions#create_rule'
      get   :edit_rule
      patch :update_rule
    end
  end


  resources :ladder_revisions, path: '/ladder_revisions'

  resources :revision_photos, only: [:destroy] do
    member do
      patch :rotate
    end
  end
  resource :demo_email, only: :show

  resources :facturacions, only: [:new, :create, :index, :edit, :update, :show, :destroy], path: 'cotizaciones' do

    member do
      get :download_solicitud_file
      get :download_cotizacion_doc_file
      get :download_cotizacion_pdf_file
      get :download_orden_compra_file
      get :download_facturacion_file
      get :download_all_files
      patch :upload_cotizacion
      patch :marcar_entregado
      patch :upload_orden_compra      
      patch :update_fecha_entrega
      patch :upload_factura
      get :manage_files
      patch :replace_file
      get :download_solicitud_template
      get :download_cotizacion_template
      get :download_cotizacion_template_og
      patch :update_price
      patch :set_fecha_venta
      patch :update_fecha_venta
      patch :update_empresa_provisional
      patch :update_n1

    end
    collection do
      get :new_bulk_upload
      post :bulk_upload
      get :new_bulk_upload_pdf
      post :bulk_upload_pdf
      get :download_all_excel
      get :export_xlsx
      get :export_monthly_report
    end


    resources :observacions, only: [:create, :edit, :update, :destroy]
  end

  resources :convenios

  resources :permisos


  get 'warnings', to: 'static_pages#warnings'
  get 'info', to: 'static_pages#info'
  get 'empresas.xlsx', to: 'static_pages#export_empresas_xlsx', as: :export_empresas
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  require "ostruct"
  require 'securerandom'
  require 'fileutils'
  require 'open3'
  def index
    if params[:facturacion_id].present?
      params[:q] ||= {}
      params[:q][:facturacion_id_eq] = params[:facturacion_id]
      @facturacion = Facturacion.find(params[:facturacion_id])
    end

    @q = Inspection.ransack(params[:q])

    @inspections = @q.result(distinct: true)
                     .where("number > 0")
                     .includes(:item, :principal, :report)
                     .order(number: :desc)
                     .then { |relation| @facturacion ? relation.where(facturacion_id: @facturacion.id) : relation }


    unless Current.user.tabla
      @pagy, @inspections = pagy_countless(@inspections, items: 10)
    end
  end

  def show


    inspection
    @item = inspection.item
    @report = Report.find_by(inspection_id: @inspection.id)

    @previous_inspection = @item.inspections.where(state: ["Cerrado", "Abierto"]).order(number: :desc).offset(1).first

    if @previous_inspection
      @show_third_radio_button = true
    else
      @show_third_radio_button = false
    end

    @last_inspection = Inspection.where(item: @item).order(number: :desc).first
    @control2 = @item.group.type_of
    if @control2 == "escala"
      @detail = LadderDetail.find_by(item_id: @item.id)
      @revision = LadderRevision.find_by(inspection_id: @inspection.id)
      @has_incomplete_revision_colors = @revision.revision_colors.exists?(color: false)

    elsif @control2 == "ascensor"
      @detail = Detail.find_by(item_id: @item.id)
      @revision = Revision.find_by(inspection_id: @inspection.id)
      @has_incomplete_revision_colors = @revision.revision_colors.exists?(color: false)

    elsif @control2 == "plat"
      @detail = Detail.find_by(item_id: @item.id)
      @revision = PlatRevision.find_by(inspection_id: @inspection.id)
      @has_incomplete_revision_colors = @revision.plat_revision_sections.exists?(color: false)
    end


    @control = @inspection == @last_inspection
    @control3 = @item.identificador.include? "CAMBIAME"
    @report = Report.find_by(inspection: inspection)
    @inspections = Inspection.where("number > 0").order(number: :desc)



    @cot0 = Facturacion.find_by(number: 0)


  end
  def new



    @inspection = Inspection.new

    authorize! @inspection
    @items = Item.all
    @item = Item.new
    @manual_action_name = "new"
    @back_path = request.referer || inspections_path
    @cot0 = Facturacion.find_by(number: 0)
  end

  def create
    copy_after   = false
    copy_from_id = nil
    @cot0 = Facturacion.find_by(number: 0)

    ActiveRecord::Base.transaction do
      @manual_action_name = inspection_params[:manual_action_name]
      @inspection = Inspection.new(inspection_params.except(:identificador, :calle, :group_id, :principal_id, :manual_action_name))

      authorize! @inspection

      control = true
      item_params = inspection_params.slice(:identificador, :group_id, :principal_id)
      item_params[:identificador] = item_params[:identificador].gsub(/\s+/, "") if item_params[:identificador].present?

      if item_params[:group_id] == "bad"
        @inspection.errors.add(:base, "Seleccione un grupo")
        control = false
      end

      if item_params[:principal_id].blank? || !Principal.exists?(item_params[:principal_id])
        @inspection.errors.add(:base, "Seleccione una empresa")
        control = false
      else
        @principal = Principal.find(item_params[:principal_id])
      end

      if item_params[:identificador].blank?
        item_params[:identificador] = "CAMBIAME(Empresa: #{item_params[:principal_id]}. Lugar de inspección: #{@inspection.place} #{SecureRandom.hex(10)})"
      end

      if control == false
        @item = Item.new(item_params)
        render :new, status: :unprocessable_entity
        return
      else
        @item = Item.where(identificador: item_params[:identificador], principal_id: @principal.id).first_or_initialize
      end

      current_group = @item.group&.id.to_s
      current_group_name = @item.group&.name
      @item.assign_attributes(item_params)
      is_new_item = @item.new_record?

      if @item.new_record? && Item.exists?(identificador: item_params[:identificador])
        @inspection.errors.add(:base, "El activo con id #{item_params[:identificador]} pertenece a la empresa #{Item.find_by(identificador: item_params[:identificador]).principal.name}")
        render :new, status: :unprocessable_entity
        return
      end

      if !@item.new_record? && current_group != item_params[:group_id]
        @inspection.errors.add(:base, "Activo con identificador #{@item.identificador} pertenece a #{current_group_name}, seleccione el grupo correspondiente")
        render :new, status: :unprocessable_entity
        return
      end


      inspection_abierta = Inspection.where(item: @item, state: "abierto").order(id: :desc).first
      if inspection_abierta
        inspection_link = helpers.link_to("Inspección N°#{inspection_abierta.number}", inspection_path(inspection_abierta), style: "color: blue; text-decoration: underline;")
        @inspection.errors.add(:base, "Ya existe una inspección abierta para este activo: #{inspection_link}".html_safe)
        render :new, status: :unprocessable_entity
        return
      end



      @item.save!
      @inspection.item = @item
      puts(@inspection.inspect)
      @inspection.save!
      @report = Report.create!(inspection: @inspection, item: @inspection.item)
      if @item.group.type_of == "escala"
        @revision = LadderRevision.create!(inspection: @inspection, item: @inspection.item)
        numbers = [0,1,2,3,4,5,6,7,8,11, 12, 13, 14, 15]
        numbers.each do |number|
          @revision.revision_colors.create!(section: number, color: false)
        end
        @detail = LadderDetail.find_or_create_by(item: @item)

      elsif @item.group.type_of == "ascensor"
        @revision = Revision.create!(inspection: @inspection, item: @inspection.item, group: @inspection.item.group)
        (0..11).each do |index|
          @revision.revision_colors.create!(section: index, color: false)
        end
        @detail = Detail.find_or_create_by(item: @item)

      elsif @item.group.type_of == "plat"
        @revision = PlatRevision.create!(inspection: @inspection, item: @inspection.item, group: @inspection.item.group)
        if @item.group.secondary_type == "plataforma"
          (0..9).each do |index|
            @revision.plat_revision_sections.create!(section: index, color: false)
          end
        elsif @item.group.secondary_type == "salvaescala"
          (0..7).each do |index|
            @revision.plat_revision_sections.create!(section: index, color: false)
          end
        end


        @detail = Detail.find_or_create_by(item: @item)


      end

      if @inspection.rerun == true
        last_inspection = @item.inspections
                               .where("number > 0")
                               .where.not(id: @inspection.id)
                               .order(number: :desc)
                               .first
        if last_inspection
          copy_after   = true
          copy_from_id = last_inspection.id
        end
      end
    end

    if copy_after
      params[:id] = @inspection.id
      params[:selected_inspection_id] = copy_from_id
      return copy
    end
    flash[:notice] = "Inspección creada con éxito"
    redirect_to inspection_path(@inspection), status: :see_other
  rescue ActiveRecord::RecordInvalid => e
    @inspection.errors.add(:base, e.record.errors.full_messages.uniq.join(', '))
    render :new, status: :unprocessable_entity
  end



  def new_with_last
    @from_last_inspection = true
    last_inspection = Inspection.find(params[:id])

    @inspection = Inspection.new(
      place: last_inspection.place,
      validation: last_inspection.validation,
      ins_date: Time.zone.today
    )

    @item = last_inspection.item
    @manual_action_name = "new_with_last"

    @cot0 = Facturacion.find_by(number: 0)
    render :new
  end

  def edit
    authorize! inspection
    #inspection_not_modifiable!(inspection)
    @manual_action_name = "edit"

    @items = Item.all
    @item = inspection.item
    @cot0 = Facturacion.find_by(number: 0)
  end







  def update_ending
    authorize! inspection
    ending = inspection_params[:ending]
    @report = Report.find_by(inspection: inspection)

    if @report.update(ending: ending)
      ending_date = ending&.to_date
      if ending_date.present?
        today = Time.zone.today
        current_result = inspection.result.to_s
        new_result = nil

        if ending_date < today
          case current_result
          when 'Aprobado'
            new_result = 'Vencido (Aprobado)'
          when 'Rechazado'
            new_result = 'Vencido (Rechazado)'
          end
        else
          case current_result
          when 'Vencido (Aprobado)'
            new_result = 'Aprobado'
          when 'Vencido (Rechazado)'
            new_result = 'Rechazado'
          end
        end

        inspection.update(result: new_result) if new_result.present?
      end
      # --------------------------------------------------------------------------------------

      flash[:notice] = "Fecha de término de certificación actualizada"
      redirect_to @inspection
    else
      render @inspection, status: :unprocessable_entity
    end
  end


  def update_inf_date
    authorize! inspection
    inf_date = inspection_params[:inf_date]
    if @inspection.update(inf_date: inf_date)
      flash[:notice] = "Fecha de emisión de informe actualizada"
      redirect_to @inspection
    else
      render @inspection, status: :unprocessable_entity
    end
  end



  def update
    authorize! inspection
    @manual_action_name = inspection_params[:manual_action_name]
    @cot0 = Facturacion.find_by(number: 0)

app/helpers/inspections_helper.rb
module InspectionsHelper

  #validation es un numero entero, pero el usuario lo debe ver como un string con la palabra años, asi que esto se encarga de eso
  def display_periodicity(validation)
    case validation
    when 1
      '1 año'
    when 2
      '2 años'
    else
      'Error al ingresar la periodicidad, por favor intente nuevamente'
    end
  end
end

app/views/inspections/_inspection.html.erb
<div id="<%= dom_id inspection %>" class="max-w-md mx-auto bg-gray-900 rounded-xl shadow-lg overflow-hidden md:max-w-2xl">
  <div class="p-8">
    <p class="text-gray-400">
      <strong class="text-gray-200 text-4xl">Inspección N°: <%= inspection.number %>  <%= inspection.name %></strong>

    </p>

    <p class="text-gray-400">
      <strong class="text-gray-200 text-2xl">Identificador: <%= link_to "#{inspection.item&.identificador}", item_path(inspection.item), class:"text-blue-500", data: { turbo_frame: "_top" } %></strong>

    </p>

    <p class="text-gray-400">
      <strong class="text-gray-200">Empresa:</strong>
      <%= link_to "#{inspection.item&.principal&.name}", principal_path(inspection.item.principal), class:"text-blue-500", data: { turbo_frame: "_top" } %>
    </p>

    <p class="text-gray-400">
      <strong class="text-gray-200">Fecha de la inspección:</strong>
      <%= format_date(inspection.ins_date) %>
    </p>

    <p class="text-gray-400">
      <strong class="text-gray-200">Periodicidad:</strong>
      <%= display_periodicity(inspection.validation) %>
    </p>

    <p class="text-gray-400">
      <strong class="text-gray-200">Clasificación:</strong>
      <%= inspection.item&.group&.name %>
    </p>


    <p class="text-gray-400">
      <strong class="text-gray-200">¿Es reinspección?</strong>
      <%= inspection.rerun ? "Sí" : "No" %>
    </p>

    <p class="text-gray-400">
      <strong class="text-gray-200">Resultado de la inspección:</strong>
      <%= inspection.result %>
    </p>


    <p class="text-gray-400">
      <strong class="text-gray-200">Fecha de término certificación:</strong>
      <%= format_date(inspection.report&.ending) %>
    </p>

    <div class="mt-4">
      <% if (controller_name == 'inspections' && action_name == 'index') || (controller_name == 'users' && action_name == 'show') || (controller_name == 'static_pages') || (controller_name == "home") %>
        <%= link_to 'Ver inspección', inspection_path(inspection), class: "inline-block px-6 py-2 border border-blue-800 text-blue-400 font-medium text-xs leading-tight uppercase rounded hover:bg-blue-800 hover:text-white focus:outline-none focus:ring-0 transition duration-150 ease-in-out", 'data-turbo-frame': "_top" %>
      <% end %>
    </div>
  </div>
</div>

app/views/inspections/edit.html.erb
<div class="max-w-4xl mx-auto sm:px-6 lg:px-8 py-8 bg-gray-800 rounded-lg shadow-md">
  <h1 class="text-2xl font-bold text-gray-100 mb-6 text-center">Modificar Inspección N° <%= @inspection.number %></h1>

  <div class="flex justify-center my-4 space-x-4">
    <%= link_to "Volver atrás", @inspection,
                class: "text-md text-gray-300 hover:text-gray-400 transition duration-150 ease-in-out px-4 py-2 border border-gray-700 rounded hover:bg-gray-700",
                data: { controller: "confirm-navigation", action: "click->confirm-navigation#confirmExit" } %>
    <%= link_to "Volver a inspecciones", inspections_path,
                class: "text-md text-blue-400 hover:text-blue-500 transition duration-150 ease-in-out px-4 py-2 border border-blue-500 rounded hover:bg-blue-800",
                data: { controller: "confirm-navigation", action: "click->confirm-navigation#confirmExit" } %>
  </div>

  <%= render "form", inspection: @inspection %>




</div>

app/views/inspections/edit_certificacion.html.erb
<div class="max-w-xl mx-auto px-4 py-6 ">
  <div class="flex items-center justify-start">
    <%= link_to "Volver a la inspección",
                inspection_path(@inspection),
                class: "inline-flex items-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-blue-400 bg-gray-800 hover:bg-blue-800 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 transition duration-150 ease-in-out" %>
  </div>
</div>

<div class="max-w-xl mx-auto my-4 px-4 py-6 bg-gray-900 rounded-lg shadow-md">
  <h1 class="text-2xl font-bold text-center text-gray-200 mb-6">Subir Certificación</h1>

  <p class="text-gray-300 mb-4">
    <strong>Última actualización:</strong>
    <%= @inspection.certificacion.attached? ? @inspection.certificacion.created_at.strftime("%d/%m/%Y %H:%M") : "No se ha subido una certificación aún." %>
  </p>

  <%= form_with(model: @inspection, url: update_certificacion_inspection_path(@inspection), method: :patch, multipart: true, class: "space-y-4") do |form| %>
    <div>
      <%= form.label :certificacion, "Subir certificación (.pdf):", class: "block text-gray-300 font-bold mb-2" %>
      <%= form.file_field :certificacion, accept: ".pdf", class: "block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" %>
    </div>

    <%= form.hidden_field :dummy_field, value: "1" %>

    <div>
      <%= form.submit "Subir", class: "w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
    </div>
  <% end %>

  <% if @inspection.certificacion.attached? %>
    <div class="mt-6 text-center">
      <%= link_to "Descargar certificación actual",
                  download_certificacion_inspection_path(@inspection),
                  class: "inline-block bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</div>

<div class="text-center mt-4">
  <%= link_to "Volver", inspection_path(@inspection), class: "inline-block text-gray-300 hover:text-white font-bold py-2 px-4" %>
</div>

app/views/inspections/edit_informe.html.erb
<div class="max-w-xl mx-auto px-4 py-6 ">

  <div class="flex items-center justify-start">
    <%= link_to "Volver a la inspección",
                inspection_path(@inspection),
                class: "inline-flex items-center px-4 py-2 border border-transparent \
                          text-base leading-6 font-medium rounded-md text-blue-400 \
                          bg-gray-800 hover:bg-blue-800 hover:text-white focus:outline-none \
                          focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 transition duration-150 ease-in-out"
    %>
  </div>
</div>
<div class="max-w-xl mx-auto my-4 px-4 py-6 bg-gray-900 rounded-lg shadow-md">
  <h1 class="text-2xl font-bold text-center text-gray-200 mb-6">Subir Informe</h1>

  <p class="text-gray-300 mb-4">
    <strong>Última actualización:</strong>
    <%= @inspection.informe.attached? ? @inspection.informe.created_at.strftime("%d/%m/%Y %H:%M") : "No se ha subido un informe aún." %>
  </p>

  <%= form_with(model: @inspection, url: update_informe_inspection_path(@inspection), method: :patch, multipart: true, class: "space-y-4") do |form| %>
    <div>
      <%= form.label :informe, "Subir informe (de preferencia .docx):", class: "block text-gray-300 font-bold mb-2" %>
      <%= form.file_field :informe, accept: ".docx,.pdf", class: "block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" %>
    </div>
    <%= form.hidden_field :dummy_field, value: "1" %>

    <div>
      <%= form.submit "Subir", class: "w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline cursor-pointer" %>
    </div>
  <% end %>

  <% if @inspection.informe.attached? %>
    <div class="mt-6 text-center">
      <%= link_to "Descargar informe actual", download_informe_inspection_path(@inspection), class: "inline-block bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</div>

<div class="text-center mt-4">
  <%= link_to "Volver", inspection_path(@inspection), class: "inline-block text-gray-300 hover:text-white font-bold py-2 px-4" %>
</div>

app/views/inspections/edit_massive_load.html.erb
<div class="max-w-xl mx-auto px-4 py-6">
  <div class="flex items-center justify-start">
    <%= link_to "Volver a inspecciones",
                inspections_path,
                class: "inline-flex items-center px-4 py-2 border border-transparent \
                          text-base leading-6 font-medium rounded-md text-blue-400 \
                          bg-gray-800 hover:bg-blue-800 hover:text-white focus:outline-none \
                          focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 transition duration-150 ease-in-out"
    %>
  </div>
</div>

<div class="max-w-xl mx-auto my-4 px-4 py-6 bg-gray-900 rounded-lg shadow-md">
  <h1 class="text-2xl font-bold text-center text-gray-200 mb-6">Carga Masiva de Archivos</h1>

  <p class="text-gray-300 mb-4">
    Sube un archivo para realizar la carga masiva de datos. Asegúrate de que el formato sea correcto antes de enviarlo.
  </p>

  <%= form_with url: update_massive_load_inspections_path, method: :patch, multipart: true, class: "space-y-4" do |form| %>
    <div>
      <%= form.label :file, "Selecciona un archivo para cargar:", class: "block text-gray-300 font-bold mb-2" %>
      <%= form.file_field :file, accept: ".csv,.xlsx", class: "block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" %>
    </div>

    <div>
      <%= form.submit "Subir Archivo", class: "w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
</div>

app/views/inspections/new.html.erb
<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 my-8">
  <h1 class="text-3xl font-bold text-gray-800 mb-8">Nueva Inspección</h1>

  <div class="mb-6">
    <%= link_to "Volver atrás", @back_path,
                class: "inline-flex items-center px-4 py-2 border border-transparent text-base leading-6 font-medium rounded-md text-blue-400 bg-gray-800 hover:bg-blue-800 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 transition duration-150 ease-in-out",
                data: { controller: "confirm-navigation", action: "click->confirm-navigation#confirmExit" } %>
  </div>




  <div class="mb-6 bg-gray-900 shadow overflow-hidden sm:rounded-lg pb-8">
    <%= render "form", inspection: @inspection %>
  </div>


</div>